/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/storefront/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get store config
         * @description The store's identity and theme. The storefront fetches this before rendering anything (cached for 20 minutes) and polls it every 20 minutes to pick up theme changes. A store without a theme gets the default preset.
         *
         *     The store is identified by the calling domain: the `X-Store-Domain` header (sent by the storefront server), else `Origin` (e.g. `https://acme.com` or `acme.com`), else `Host`. Responds 404 `Store not found` when no active store uses that domain.
         */
        get: operations["storefrontGetConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storefront/perfumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List perfumes
         * @description Perfumes in the store's catalogue, ordered by name, with their notes and inventory.
         *
         *     The store is identified by the calling domain: the `X-Store-Domain` header (sent by the storefront server), else `Origin` (e.g. `https://acme.com` or `acme.com`), else `Host`. Responds 404 `Store not found` when no active store uses that domain.
         */
        get: operations["storefrontListPerfumes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storefront/perfumes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a perfume
         * @description One perfume with its category, note pyramid and inventory.
         *
         *     The store is identified by the calling domain: the `X-Store-Domain` header (sent by the storefront server), else `Origin` (e.g. `https://acme.com` or `acme.com`), else `Host`. Responds 404 `Store not found` when no active store uses that domain.
         */
        get: operations["storefrontGetPerfume"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Everything the storefront needs before it renders: store identity and theme. */
        StoreConfig: {
            store: {
                /** @example Acme Perfumes */
                name: string;
                /** @example acme */
                slug: string;
            };
            theme: components["schemas"]["Theme"];
        };
        /** @description Storefront design tokens. Set per tenant by the superadmin. */
        Theme: {
            /**
             * @description The preset this theme started from
             * @enum {string}
             */
            preset: "palette" | "noir" | "rose" | "amber" | "aqua";
            colors: components["schemas"]["ThemeColors"];
            /**
             * @description Base corner radius in rem; buttons, inputs and cards derive from it
             * @example 0.25
             */
            radius: number;
            fonts: {
                /** @enum {string} */
                heading: "jost" | "cormorant-garamond" | "playfair-display" | "nunito-sans" | "poppins";
                /** @enum {string} */
                body: "jost" | "cormorant-garamond" | "playfair-display" | "nunito-sans" | "poppins";
            };
            /**
             * @description Transition speed, hover lift, image zoom and slider autoplay
             * @enum {string}
             */
            motion: "none" | "subtle" | "lively";
            productCard: {
                /** @enum {string} */
                imageAspect: "square" | "portrait";
                /**
                 * @description `swap` shows the second product image on hover
                 * @enum {string}
                 */
                hover: "none" | "zoom" | "swap";
                showBrand: boolean;
            };
            buttons: {
                uppercase: boolean;
                /** @enum {string} */
                style: "solid" | "outline";
            };
        };
        ThemeColors: {
            /**
             * @description Page background
             * @example #111111
             */
            background: string;
            /**
             * @description Main text
             * @example #111111
             */
            foreground: string;
            /**
             * @description Product cards, panels, dropdowns
             * @example #111111
             */
            card: string;
            /** @example #111111 */
            cardForeground: string;
            /**
             * @description Primary buttons and key actions
             * @example #111111
             */
            primary: string;
            /** @example #111111 */
            primaryForeground: string;
            /**
             * @description Secondary buttons, chips
             * @example #111111
             */
            secondary: string;
            /** @example #111111 */
            secondaryForeground: string;
            /**
             * @description Subtle backgrounds (sections, inputs)
             * @example #111111
             */
            muted: string;
            /**
             * @description Secondary text
             * @example #111111
             */
            mutedForeground: string;
            /**
             * @description Highlights: links on hover, badges, active states
             * @example #111111
             */
            accent: string;
            /** @example #111111 */
            accentForeground: string;
            /**
             * @description Borders and dividers
             * @example #111111
             */
            border: string;
            /**
             * @description Focus outline
             * @example #111111
             */
            ring: string;
            /**
             * @description Sale prices and badges
             * @example #111111
             */
            sale: string;
            /** @example #111111 */
            saleForeground: string;
            /**
             * @description Announcement bar background
             * @example #111111
             */
            announcement: string;
            /** @example #111111 */
            announcementForeground: string;
            /**
             * @description Footer background
             * @example #111111
             */
            footer: string;
            /** @example #111111 */
            footerForeground: string;
        };
        ErrorResponse: {
            error: {
                /** @example Validation failed */
                message: string;
                /** @description Only on validation errors: one entry per invalid field */
                details?: {
                    /**
                     * @description The invalid field
                     * @example limit
                     */
                    path: string;
                    /** @example Too big: expected number to be <=100 */
                    message: string;
                }[];
            };
        };
        /** @description A perfume as shown on the storefront */
        StorefrontPerfume: {
            /**
             * Format: uuid
             * @example 13c8666c-69d8-466e-b23e-cff7ac9d4e8f
             */
            id: string;
            /** @example Midnight Oud */
            name: string;
            /** @example Acme Perfumes */
            brand: string;
            /** @example Smoky oud and rose over warm amber. */
            description: string | null;
            /** @description Storefront category, e.g. Men, Women or Unisex */
            category: {
                /** @example Unisex */
                name: string;
                /** @example unisex */
                slug: string;
            };
            notes: {
                /** @example Oud */
                name: string;
                /**
                 * @description Where the note sits in the fragrance pyramid
                 * @enum {string}
                 */
                position: "TOP" | "HEART" | "BASE";
                /** @description Olfactory family, shared by every store */
                noteCategory: {
                    /** @example Woody */
                    name: string;
                    /** @example woody */
                    slug: string;
                } | null;
            }[];
            /** @description Sellable sizes, smallest first */
            inventory: {
                /** @example ACME-MIDNIGHT-OUD-50 */
                sku: string;
                /**
                 * @description Bottle size in millilitres
                 * @example 50
                 */
                sizeMl: number;
                /**
                 * @description Price in minor units (cents)
                 * @example 12900
                 */
                price: number;
                inStock: boolean;
            }[];
        };
    };
    responses: {
        /** @description Unexpected server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request failed validation. `details` lists each invalid field. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    storefrontGetConfig: {
        parameters: {
            query?: never;
            header?: {
                /** @description Domain of the store being browsed. Sent by the storefront server. */
                "x-store-domain"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The store config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StoreConfig"];
                    };
                };
            };
            /** @description Store not found: no active store uses the calling domain. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    storefrontListPerfumes: {
        parameters: {
            query?: {
                /** @description Only perfumes in this category (its slug) */
                category?: string;
                /** @description Maximum number of perfumes to return */
                limit?: number;
            };
            header?: {
                /** @description Domain of the store being browsed. Sent by the storefront server. */
                "x-store-domain"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The perfumes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StorefrontPerfume"][];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Store not found: no active store uses the calling domain. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    storefrontGetPerfume: {
        parameters: {
            query?: never;
            header?: {
                /** @description Domain of the store being browsed. Sent by the storefront server. */
                "x-store-domain"?: string;
            };
            path: {
                /** @description Perfume ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The perfume */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StorefrontPerfume"];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            /** @description Perfume not found in this store, or store not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
}
